# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 761b13889fd3180e9737ea154649fa5460b311ed79ccd4623c9f09b7f23453328f1aa17bc704a0f3c52a21385578f5a38a98938bdbb3c13406479596cb466fdc

test:
  secret_key_base: d9dfdd51dbe79128ab98a74cb8f66c3ecf2c31e23c5d996d85118103eabf0c1e2143f8d5bad27e40388512c12fc4556c9b848060822c2a7dfd30d05a1e8709a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
